"""0003 remaining modules

Revision ID: cced014e9c3a
Revises: 0002_w1_platform
Create Date: 2026-09-30 15:11:28.804307

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

_SCHEMAS = ("audit", "evaluation", "execution", "model_config", "planning", "profiling", "validation",)


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def _sch(name: str) -> str | None:
    """Schema name on PostgreSQL; None on SQLite (single namespace)."""
    return name if _is_postgres() else None


def _create_schemas() -> None:
    if _is_postgres():
        for _s in _SCHEMAS:
            op.execute(sa.schema.CreateSchema(_s, if_not_exists=True))


revision: str = 'cced014e9c3a'
down_revision: str | Sequence[str] | None = '0002_w1_platform'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    _create_schemas()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_role', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    schema=_sch('audit')
    )
    op.create_index('ix_audit_events_correlation_id', 'audit_events', ['correlation_id'], unique=False, schema=_sch('audit'))
    op.create_index('ix_audit_events_event_type', 'audit_events', ['event_type'], unique=False, schema=_sch('audit'))
    op.create_index('ix_audit_events_occurred_at', 'audit_events', ['occurred_at'], unique=False, schema=_sch('audit'))
    op.create_table('benchmark_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('object_keys', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_sets')),
    sa.UniqueConstraint('name', name=op.f('uq_benchmark_sets_name')),
    schema=_sch('evaluation')
    )
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('exported_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("format IN ('xlsx', 'csv', 'pipeline')", name=op.f('ck_exports_ck_exports_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports')),
    schema=_sch('execution')
    )
    op.create_index(op.f('ix_execution_exports_plan_id'), 'exports', ['plan_id'], unique=False, schema=_sch('execution'))
    op.create_table('rollbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('from_version_no', sa.Integer(), nullable=False),
    sa.Column('to_version_no', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rollbacks')),
    schema=_sch('execution')
    )
    op.create_index(op.f('ix_execution_rollbacks_plan_id'), 'rollbacks', ['plan_id'], unique=False, schema=_sch('execution'))
    op.create_table('model_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('credential_ciphertext', sa.Text(), nullable=True),
    sa.Column('credential_last4', sa.String(length=4), nullable=True),
    sa.Column('allow_data_sharing', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_configs')),
    schema=_sch('model_config')
    )
    op.create_index('uq_model_configs_one_active', 'model_configs', ['is_active'], unique=True, schema=_sch('model_config'), postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
    op.create_table('plan_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("decision IN ('pending', 'accepted', 'edited', 'rejected')", name=op.f('ck_plan_steps_ck_plan_steps_decision')),
    sa.CheckConstraint("operation IN ('replace_value', 'fill_missing', 'drop_column', 'cast_type', 'derive_column', 'expand_nested', 'deduplicate', 'standardise_format')", name=op.f('ck_plan_steps_ck_plan_steps_operation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_steps')),
    sa.UniqueConstraint('plan_id', 'step_no', name='uq_plan_steps_plan_id_step_no'),
    schema=_sch('planning')
    )
    op.create_index(op.f('ix_planning_plan_steps_plan_id'), 'plan_steps', ['plan_id'], unique=False, schema=_sch('planning'))
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_estimated_loss', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('loss_threshold', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'in_review', 'approved', 'rejected', 'superseded')", name=op.f('ck_plans_ck_plans_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    schema=_sch('planning')
    )
    op.create_index(op.f('ix_planning_plans_dataset_id'), 'plans', ['dataset_id'], unique=False, schema=_sch('planning'))
    op.create_table('column_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('physical_type', sa.String(length=100), nullable=False),
    sa.Column('semantic_type', sa.String(length=100), nullable=False),
    sa.Column('null_count', sa.Integer(), nullable=False),
    sa.Column('null_pct', sa.Float(), nullable=False),
    sa.Column('distinct_count', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Text(), nullable=True),
    sa.Column('max_value', sa.Text(), nullable=True),
    sa.Column('mean_value', sa.Float(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_column_profiles')),
    schema=_sch('profiling')
    )
    op.create_index(op.f('ix_profiling_column_profiles_dataset_id'), 'column_profiles', ['dataset_id'], unique=False, schema=_sch('profiling'))
    op.create_table('inferred_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('expression', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('evidence_rows', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("rule_type IN ('entity_group', 'arithmetic', 'primary_key', 'one_to_many', 'semantic_type', 'cross_field_fill', 'all_null')", name=op.f('ck_inferred_rules_ck_inferred_rules_rule_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inferred_rules')),
    schema=_sch('profiling')
    )
    op.create_index(op.f('ix_profiling_inferred_rules_dataset_id'), 'inferred_rules', ['dataset_id'], unique=False, schema=_sch('profiling'))
    op.create_table('profile_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('profiled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_runs')),
    schema=_sch('profiling')
    )
    op.create_index(op.f('ix_profiling_profile_runs_dataset_id'), 'profile_runs', ['dataset_id'], unique=True, schema=_sch('profiling'))
    op.create_table('reconciliations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.Text(), nullable=False),
    sa.Column('source_value', sa.Text(), nullable=False),
    sa.Column('output_value', sa.Text(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliations')),
    schema=_sch('validation')
    )
    op.create_index(op.f('ix_validation_reconciliations_plan_id'), 'reconciliations', ['plan_id'], unique=False, schema=_sch('validation'))
    op.create_table('test_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('target_step_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('unit', 'integration')", name=op.f('ck_test_cases_ck_test_cases_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_cases')),
    schema=_sch('validation')
    )
    op.create_index(op.f('ix_validation_test_cases_plan_id'), 'test_cases', ['plan_id'], unique=False, schema=_sch('validation'))
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('benchmark_set_id', sa.Uuid(), nullable=False),
    sa.Column('model_config_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','succeeded','failed')", name=op.f('ck_evaluation_runs_status')),
    sa.ForeignKeyConstraint(['benchmark_set_id'], ['evaluation.benchmark_sets.id'], name=op.f('fk_evaluation_runs_benchmark_set_id_benchmark_sets')),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_config.model_configs.id'], name=op.f('fk_evaluation_runs_model_config_id_model_configs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs')),
    schema=_sch('evaluation')
    )
    op.create_table('pipeline_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot_object_key', sa.Text(), nullable=False),
    sa.Column('inverse_operation', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('executed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['planning.plan_steps.id'], name=op.f('fk_pipeline_versions_step_id_plan_steps')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_versions')),
    sa.UniqueConstraint('plan_id', 'version_no', name=op.f('uq_pipeline_versions_plan_id')),
    schema=_sch('execution')
    )
    op.create_index(op.f('ix_execution_pipeline_versions_plan_id'), 'pipeline_versions', ['plan_id'], unique=False, schema=_sch('execution'))
    op.create_table('loss_estimates',
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('rows_affected', sa.Integer(), nullable=False),
    sa.Column('columns_affected', sa.Integer(), nullable=False),
    sa.Column('cells_affected', sa.Integer(), nullable=False),
    sa.Column('estimated_loss', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['planning.plan_steps.id'], name=op.f('fk_loss_estimates_step_id_plan_steps')),
    sa.PrimaryKeyConstraint('step_id', name=op.f('pk_loss_estimates')),
    schema=_sch('planning')
    )
    op.create_table('test_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("phase IN ('before', 'after')", name=op.f('ck_test_runs_ck_test_runs_phase')),
    sa.CheckConstraint("result IN ('passed', 'failed', 'error')", name=op.f('ck_test_runs_ck_test_runs_result')),
    sa.ForeignKeyConstraint(['test_case_id'], ['validation.test_cases.id'], name=op.f('fk_test_runs_test_case_id_test_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_runs')),
    schema=_sch('validation')
    )
    op.create_index(op.f('ix_validation_test_runs_test_case_id'), 'test_runs', ['test_case_id'], unique=False, schema=_sch('validation'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_test_runs_test_case_id'), table_name='test_runs', schema=_sch('validation'))
    op.drop_table('test_runs', schema=_sch('validation'))
    op.drop_table('loss_estimates', schema=_sch('planning'))
    op.drop_index(op.f('ix_execution_pipeline_versions_plan_id'), table_name='pipeline_versions', schema=_sch('execution'))
    op.drop_table('pipeline_versions', schema=_sch('execution'))
    op.drop_table('evaluation_runs', schema=_sch('evaluation'))
    op.drop_index(op.f('ix_validation_test_cases_plan_id'), table_name='test_cases', schema=_sch('validation'))
    op.drop_table('test_cases', schema=_sch('validation'))
    op.drop_index(op.f('ix_validation_reconciliations_plan_id'), table_name='reconciliations', schema=_sch('validation'))
    op.drop_table('reconciliations', schema=_sch('validation'))
    op.drop_index(op.f('ix_profiling_profile_runs_dataset_id'), table_name='profile_runs', schema=_sch('profiling'))
    op.drop_table('profile_runs', schema=_sch('profiling'))
    op.drop_index(op.f('ix_profiling_inferred_rules_dataset_id'), table_name='inferred_rules', schema=_sch('profiling'))
    op.drop_table('inferred_rules', schema=_sch('profiling'))
    op.drop_index(op.f('ix_profiling_column_profiles_dataset_id'), table_name='column_profiles', schema=_sch('profiling'))
    op.drop_table('column_profiles', schema=_sch('profiling'))
    op.drop_index(op.f('ix_planning_plans_dataset_id'), table_name='plans', schema=_sch('planning'))
    op.drop_table('plans', schema=_sch('planning'))
    op.drop_index(op.f('ix_planning_plan_steps_plan_id'), table_name='plan_steps', schema=_sch('planning'))
    op.drop_table('plan_steps', schema=_sch('planning'))
    op.drop_index('uq_model_configs_one_active', table_name='model_configs', schema=_sch('model_config'), postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
    op.drop_table('model_configs', schema=_sch('model_config'))
    op.drop_index(op.f('ix_execution_rollbacks_plan_id'), table_name='rollbacks', schema=_sch('execution'))
    op.drop_table('rollbacks', schema=_sch('execution'))
    op.drop_index(op.f('ix_execution_exports_plan_id'), table_name='exports', schema=_sch('execution'))
    op.drop_table('exports', schema=_sch('execution'))
    op.drop_table('benchmark_sets', schema=_sch('evaluation'))
    op.drop_index('ix_audit_events_occurred_at', table_name='audit_events', schema=_sch('audit'))
    op.drop_index('ix_audit_events_event_type', table_name='audit_events', schema=_sch('audit'))
    op.drop_index('ix_audit_events_correlation_id', table_name='audit_events', schema=_sch('audit'))
    op.drop_table('audit_events', schema=_sch('audit'))
    # ### end Alembic commands ###
